/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DaysIndexImport } from './routes/days/index'
import { Route as DaysDayIdImport } from './routes/days/$dayId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DaysIndexRoute = DaysIndexImport.update({
  id: '/days/',
  path: '/days/',
  getParentRoute: () => rootRoute,
} as any)

const DaysDayIdRoute = DaysDayIdImport.update({
  id: '/days/$dayId',
  path: '/days/$dayId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/days/$dayId': {
      id: '/days/$dayId'
      path: '/days/$dayId'
      fullPath: '/days/$dayId'
      preLoaderRoute: typeof DaysDayIdImport
      parentRoute: typeof rootRoute
    }
    '/days/': {
      id: '/days/'
      path: '/days'
      fullPath: '/days'
      preLoaderRoute: typeof DaysIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/days/$dayId': typeof DaysDayIdRoute
  '/days': typeof DaysIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/days/$dayId': typeof DaysDayIdRoute
  '/days': typeof DaysIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/days/$dayId': typeof DaysDayIdRoute
  '/days/': typeof DaysIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/days/$dayId' | '/days'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/days/$dayId' | '/days'
  id: '__root__' | '/' | '/days/$dayId' | '/days/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaysDayIdRoute: typeof DaysDayIdRoute
  DaysIndexRoute: typeof DaysIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaysDayIdRoute: DaysDayIdRoute,
  DaysIndexRoute: DaysIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/days/$dayId",
        "/days/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/days/$dayId": {
      "filePath": "days/$dayId.tsx"
    },
    "/days/": {
      "filePath": "days/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
